# Generated by Django 2.1.7 on 2022-11-10 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('name_client', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Minimarket',
            fields=[
                ('name_mini', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('phone_mini', models.CharField(max_length=15)),
                ('rubro', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrebolsa.Cliente')),
            ],
        ),
    ]
