# Generated by Django 2.1.7 on 2022-11-10 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrebolsa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('name_cat', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('name_prod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrebolsa.Categoria')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrebolsa.Cliente')),
            ],
        ),
    ]
