# Generated by Django 2.1.7 on 2022-11-10 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrebolsa', '0002_categoria_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50, verbose_name='Categoria/Asunto')),
                ('detail', models.TextField(verbose_name='Detalle')),
            ],
        ),
        migrations.AlterField(
            model_name='categoria',
            name='name_cat',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='name_client',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='minimarket',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='minimarket',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrebolsa.Cliente', verbose_name='Dueño'),
        ),
        migrations.AlterField(
            model_name='minimarket',
            name='name_mini',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='minimarket',
            name='phone_mini',
            field=models.CharField(max_length=15, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrebolsa.Categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrebolsa.Cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='name_prod',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='price',
            field=models.IntegerField(verbose_name='Precio'),
        ),
    ]
