# Generated by Django 2.1.7 on 2022-11-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrebolsa', '0003_auto_20221110_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(default=None, upload_to='productos'),
            preserve_default=False,
        ),
    ]
