# Generated by Django 2.1.7 on 2022-11-11 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrebolsa', '0004_producto_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='image',
            new_name='imagen',
        ),
    ]
