# Generated by Django 2.1.7 on 2022-11-11 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrebolsa', '0006_auto_20221111_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='image',
        ),
    ]
