# Generated by Django 2.1.7 on 2022-11-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrebolsa', '0007_remove_producto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(default=1, upload_to='productos'),
            preserve_default=False,
        ),
    ]
