# Generated by Django 2.1.7 on 2022-11-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrebolsa', '0008_producto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.IntegerField(default=1, max_length=6, primary_key=True, serialize=False, verbose_name='Codigo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='name_prod',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
