# Generated by Django 2.1.7 on 2022-11-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrebolsa', '0009_auto_20221129_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo'),
        ),
    ]
