# Generated by Django 2.1.7 on 2022-11-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrebolsa', '0011_auto_20221129_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Codigo'),
        ),
    ]
