# Generated by Django 2.1.7 on 2022-12-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrebolsa', '0012_auto_20221129_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='minimarket',
            name='image',
            field=models.ImageField(default=2, upload_to='minimarket'),
            preserve_default=False,
        ),
    ]
